- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
Added Navbar at the bottom. 
Includes icons for the links to the different pages we will eventually have.
Login and sign up buttons created
> Navbar V1.0

- Gemfile
- Gemfile.lock
- app/views/activities/index.html.erb
- db/migrate/20241126140056_add_attributes_to_users.rb
- db/migrate/20241126143145_remove_type_field_from_activities_table.rb
- db/migrate/20241126143531_add_category_to_activities.rb
- db/schema.rb
- db/seeds.rb
Changed the Activities table to replace the type attribute with category (type was causing an error).
Added the Faker gem
Seeded the DB with 5 users
Seeded the DB with 5 clubs, each assigned to a user 
Seeded the DB with 25 activities, each assigned to a club (5 per club)
Added the activities attributes to the Activities index page as Embedded Ruby to test the seed
> Seeded the DB with 5 users, who each have a club, which each have 5 activities

- app/controllers/activities_controller.rb
- app/views/activities/index.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_search_bar.html.erb
I created a pretty search bar through a form and using render. With a splash of css.
>  creating search bar

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_search_bar.html.erb
Finsihed home page.
Search bar styling
button formats
> Stage 2 complete

- app/assets/stylesheets/pages/_activities.scss
- app/controllers/activities_controller.rb
- app/views/activities/show.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_search_bar.html.erb
just did the activity page as well as fixed the problem with the search bar (hopefully its good now)
> worked on activity page

- app/assets/stylesheets/pages/_activities-index.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/activities/index.html.erb
Added a better layout to the index page
> V1 index page

- app/views/shared/_search_bar.html.erb
just changed the path from root to activities
> fix search bar

- app/assets/stylesheets/pages/_activities-index.scss
- app/views/activities/index.html.erb
- app/views/shared/_search_bar.html.erb
- Improved the front-end for it to look like our Figma
- Added the right ERB field to have the right Data appear from our seeds
> Set the basis of index layout and data (Controller)

- app/assets/stylesheets/pages/_activities.scss
- app/views/activities/index.html.erb
- app/views/activities/show.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
i fixed and added a nav bar to the bottom of the page.
> activitypage2

- app/views/shared/_navbar.html.erb
i added so that in the navbar, if you are not signed in and press on one of the icons it will bring you to the sign up form
> added to the navbar

- app/assets/stylesheets/pages/_home.scss
- app/controllers/activities_controller.rb
- app/controllers/application_controller.rb
- app/views/activities/index.html.erb
- app/views/devise/registrations/new.html.erb
Fixed user sign up not working - added the right configuration in the Application Controller
Linked category items to the right values/params
Updated the Activities Controller to enable the search features
> Filtering by category on activities index page works properly

- app/controllers/clubs_controller.rb
- app/views/shared/_navbar.html.erb
i added skip_before_action :authenticate_user!, only: :show to club controller 
and  skip_before_action :authenticate_user!, only: %i[show index] in activities controller
> non logged in users conditions

- app/assets/stylesheets/pages/_club.scss
- app/javascript/controllers/toggle_text_controller.js
- app/views/clubs/show.html.erb
Cleaned the button
No white bar at the top of screen
> button fix

- app/assets/stylesheets/pages/_activities-index.scss
- app/controllers/activities_controller.rb
- app/views/activities/index.html.erb
- db/seeds.rb
24 activities (3 per category), with realistic names
> Seeded the app with more realistic data

- app/views/devise/registrations/new.html.erb
i added mx-auto to the class of each content so that the boxes aligned to the centere of the page and the text
> fix align of content in sign up page

- app/controllers/activities_controller.rb
- app/controllers/bookings_controller.rb
- app/models/activity.rb
- app/models/booking.rb
- app/models/user.rb
- app/views/activities/show.html.erb
- app/views/shared/_flashes.html.erb
- config/routes.rb
- db/migrate/20241129134439_create_bookings.rb
- db/schema.rb
- test/controllers/bookings_controller_test.rb
- test/models/booking_test.rb
Generated the bookings model with foreign keys -> belongs to user and activity
Updated the User and Activity models to add has_many bookings
Created a migration
Generated the Bookings Controller with a Create action
Added the right routes to only :create
Implemented a conditional to show a Login button if the user isn't logged in, and the Attend button if he is
Coded a message to appear if the user clicks Attend on a show page
> Bookings done

- app/assets/stylesheets/pages/_club.scss
- app/assets/stylesheets/pages/_my_clubs.scss
- app/controllers/clubs_controller.rb
- app/models/club.rb
- app/views/clubs/my_clubs.html.erb
- app/views/clubs/new.html.erb
- app/views/clubs/show.html.erb
- config/routes.rb
Created a dashboard where 'my clubs' are displayed
add a club
delete club
clubs are dynamic and created clubs can be viewed with their relevant information
> added my clubs actions

- app/assets/images/backbutton.svg
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_club.scss
- app/assets/stylesheets/pages/_my_clubs.scss
- app/assets/stylesheets/pages/_new.scss
- app/views/activities/show.html.erb
- app/views/clubs/my_clubs.html.erb
- app/views/clubs/show.html.erb
The display looks better. 
Made the back button look a bit more sleek as I think it was a bit big and stood out against the rest of the page
I made the club-cards much smaller so that they appear more professional
I added some dynamic details that appear on the dash (i.e date of club creation, number of clubs, username, name etc)
> finsihed dashboard

- db/seeds.rb
change the activities and linked the gight club to it as well as added the right pictures to the activities
> fix the seed problem

- app/assets/stylesheets/pages/_home.scss
- app/controllers/bookings_controller.rb
- app/controllers/feedbacks_controller.rb
- app/models/activity.rb
- app/models/feedback.rb
- app/models/user.rb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/migrate/20241202104555_create_feedbacks.rb
- db/schema.rb
- test/controllers/feedbacks_controller_test.rb
- test/models/feedback_test.rb
Changed the navbar to add a third element "Activity"
Generated model for Feedback with the right associations (belongs to user and activity)
Generated migration
Created routes for Feedback
Generated controller for Feedbacks with one action: Create
> Created Feedback structure

- app/assets/stylesheets/pages/_my_clubs.scss
- app/javascript/controllers/clubmap_controller.js
- app/views/clubs/my_clubs.html.erb
Finished Settings page
Fixed map bug with undefined
> added settings page

- app/assets/stylesheets/pages/_activities-index.scss
- app/assets/stylesheets/pages/_activities.scss
- app/assets/stylesheets/pages/_my_clubs.scss
- app/assets/stylesheets/pages/_profile.scss
- app/controllers/users_controller.rb
- app/views/activities/show.html.erb
- app/views/clubs/my_clubs.html.erb
- app/views/users/profile.html.erb
There were overlapping CSS mistakes between the profile image and the other pages
> fixed the issues with css

- app/assets/stylesheets/pages/_profile.scss
- app/views/users/profile.html.erb
i fixed the css on the profile page by adding  align-items: flex-start; and  padding-left: 17px; as well as aligning the tile with padding.
> fix profile page

- app/assets/stylesheets/pages/_profile.scss
changed the space between text and button, as well as space in the box. Changed the size of the button and it's border and then added a margin to the right of the page
> fix part two of profile page

- app/assets/stylesheets/pages/_new.scss
- app/assets/stylesheets/pages/_sign_up.scss
i just fixed the form so that everything is centered in the login page and sign-up page
> fix the centering of the text

- app/assets/stylesheets/pages/_account.scss
- app/assets/stylesheets/pages/_club.scss
- app/models/club.rb
- app/views/clubs/show.html.erb
Finshed with the activity functions
DOJO dynamic image for clubs
> last edits

- app/assets/stylesheets/pages/_my_activities.scss
- app/assets/stylesheets/pages/_profile.scss
- app/views/clubs/manage_dojos.html.erb
deleted second add activity button
> fixed bugs

- app/views/clubs/show.html.erb
removed the if statement in the show page for clubs
> fix part 2

- app/assets/stylesheets/pages/_account.scss
- app/assets/stylesheets/pages/_club.scss
- app/assets/stylesheets/pages/_feed.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/clubs_controller.rb
- app/controllers/messages_controller.rb
- app/javascript/controllers/activities_feed_toggle_controller.js
- app/models/club.rb
- app/views/clubs/show.html.erb
Modified the Clubs and Messages controllers to make the messages feature work on Show page
Created a new CSS file for feed and styled the feed and messages
Generated Stimulus controller for the Activities/Feed toggle on Club show page
Implemented the right Stimulus code to enable the toggle feature
Next step is to ajaxify the messages so that the page doesn't reload with each new message post
> Implemented Feed feature + Stimulus for better UX

- app/assets/stylesheets/pages/_profile.scss
- app/controllers/users_controller.rb
- app/views/users/profile.html.erb
I fixed the container on the profile page, then I changed the feedbacks so that it is dynamic to what you as a user wrote
> fixed profile page

- app/assets/stylesheets/pages/_profile.scss
- app/views/users/profile.html.erb
I added a back button to the profile page and fixed a bug by adding an if statement to the feedbacks
> add back button

- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/pages/_activities-index.scss
- app/assets/stylesheets/pages/_search_bar.scss
- app/controllers/users_controller.rb
- app/javascript/controllers/map_controller.js
- app/javascript/controllers/search_controller.js
- app/models/user.rb
- app/views/activities/_markers.html.erb
- app/views/activities/index.html.erb
- app/views/shared/_search_bar.html.erb
- app/views/users/profile.html.erb
Added search JS that hides the screen while searching for something
> added search JS

- app/assets/stylesheets/pages/_activities.scss
- app/assets/stylesheets/pages/_feed.scss
- app/controllers/clubs_controller.rb
- app/javascript/controllers/activities_feed_toggle_controller.js
- app/models/user.rb
- app/views/activities/show.html.erb
- app/views/clubs/show.html.erb
- app/views/devise/registrations/new.html.erb
- db/seeds.rb
Proper users…
300 users, plus:
Salman Tsagaraev
Madeleine de Kerchove
Pedro Vilarinho
Babadi MUKANYA
Sándor Lázár
François Catelas
Maximilian Conru
Leonidas Zamora
… these 8 users in particular need the following data:
Profile pics (stored in Cloudinary)
Activities they attended (only past activities)
Feedbacks given to activities they attended
Messages added to the feeds of activities they attended / will attend
First Name
Last Name
Username
Email
Password set to 123456
Activities with:
Realistic titles
Realistic addresses
Realistic pictures (stored in Cloudinary)
Realistic descriptions (around 300 characters)
Fixed times (eg. 19.30)
Some activities must be in the past so that users can have attended them and provided feedback
Feedbacks (given by the users) - 90% need to be true …
> Seeds on Steroids

- app/views/clubs/show.html.erb
Made sure the feed messages appear in the right order
> Improved Feed

- app/assets/stylesheets/pages/_club.scss
- app/assets/stylesheets/pages/_search_bar.scss
- app/controllers/clubs_controller.rb
- app/controllers/feedbacks_controller.rb
- app/views/activities/my_activities.html.erb
- app/views/activities/show.html.erb
- app/views/clubs/show.html.erb
added feedback to the club page and created and if/else statement that shows the feedback of and activity only if the activity is in the past
> clubpage and feedbakc

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_account.scss
- app/assets/stylesheets/pages/_activities-index.scss
- app/assets/stylesheets/pages/_activities.scss
- app/assets/stylesheets/pages/_club.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_search_bar.scss
- app/views/activities/show.html.erb
- app/views/users/account.html.erb
Chose a different font and spread it across the app
Fixed the index page 
Fixed the alignment in the settings
> Changed fonts

- app/assets/stylesheets/pages/_club.scss
- app/assets/stylesheets/pages/_feed.scss
- app/controllers/clubs_controller.rb
- app/controllers/feedbacks_controller.rb
- app/javascript/controllers/activities_feed_toggle_controller.js
- app/views/clubs/show.html.erb
- app/views/users/account.html.erb
- db/seeds.rb
Improved the feed function so the chat box is sticky at the bottom
Added user profile pics
Added upcoming and attended activities differentiation to the club show page + made them clickable
Added dynamic user profile pic to account show pages
Changed the Seed so user maddie@dojo.com has less activities
Commented the code that made Feedbacks unique in the Feedbacks Controller
> Improved club show

- app/javascript/controllers/map_controller.js
Made the map zoom feature for a fun dynamic intro
> made the map move out slow
